[phases.setup]
nixPkgs = ["nodejs_22", "npm"]

[phases.build]
cmds = ["npm install", "npm run build:seo"]

[start]
cmd = "sed -i 's|try_files {path} /index.html|try_files {path} {path}/index.html /index.html|' /assets/Caddyfile && caddy run --config /assets/Caddyfile --adapter caddyfile 2>&1"
